name: Frontend Test
run-name: Test ESLint and Prettier.
on: [push]
jobs:
  Lint-Test:
    runs-on: ubuntu-latest
    steps:
      - run: cd react-custom-datetime-picker
      - run: yarn install
      - run: yarn lint
