name: Frontend Test
run-name: Test ESLint and Prettier.
on: [push]
jobs:
  Lint-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: ci
        run: yarn ci
      - name: ESLint
        run: yarn run lint
